import test from "node:test";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SwarmRouter } from "../src/router.mjs";
const git = (cwd, args) => execFileSync("git", ["-C", cwd, ...args], { encoding: "utf8" }).trim();
const task = (id, title, dependsOn = []) => ({ id, title, prompt: title, primaryDomain: "backend", supportingDomains: [], riskFlags: [], humanApprovalRequired: false, estimatedTokens: 20, dependsOn, allowedPaths: [`src/${id}.mjs`], acceptanceChecks: [] });
class Client extends EventEmitter {
  constructor(plan) { super(); this.plan = plan; this.n = 0; this.threads = new Map(); this.bases = new Map(); }
  async connect() {} shutdown() {} diagnostics() { return {}; } async request(method) { return method === "account/read" ? { account: {} } : method === "account/usage/read" ? { dailyUsageBuckets: [] } : { rateLimits: null }; }
  async startThread({ cwd }) { const id = `t${++this.n}`; this.threads.set(id, { cwd, goal: "" }); return { thread: { id } }; } async setGoal({ threadId, objective }) { this.threads.get(threadId).goal = objective; } async startTurn({ threadId }) { return { turn: { id: `${threadId}-turn` } }; }
  async waitForTurn(threadId, turnId) { const t = this.threads.get(threadId); if (/^Write A\n\nWrite A$/.test(t.goal)) { this.bases.set("a", git(t.cwd, ["rev-parse", "HEAD"])); writeFileSync(join(t.cwd, "src", "writer-a.mjs"), "export const a = true;\n"); } if (/^Write B\n\nWrite B$/.test(t.goal)) { this.bases.set("b", git(t.cwd, ["rev-parse", "HEAD"])); writeFileSync(join(t.cwd, "src", "writer-b.mjs"), "export const b = true;\n"); } return { id: turnId, status: "completed" }; }
  async readThread({ threadId }) { const goal = this.threads.get(threadId).goal; const text = /^Bootstrap/.test(goal) ? "```json\n{\"summary\":\"ok\",\"assumptions\":[],\"risks\":[],\"humanGates\":[]}\n```" : /^Plan /.test(goal) ? `\`\`\`json\n${JSON.stringify(this.plan)}\n\`\`\`` : /^Security review:/.test(goal) || /^QA:/.test(goal) ? "```json\n{\"verdict\":\"pass\",\"summary\":\"ok\",\"findings\":[],\"executedChecks\":[],\"notRunChecks\":[]}\n```" : "done"; return { thread: { turns: [{ id: `${threadId}-turn`, items: [{ type: "agentMessage", text }] }] } }; }
}
function setup(plan) { const root = mkdtempSync(join(tmpdir(), "lineage-")); git(root, ["init", "-b", "main"]); mkdirSync(join(root, "src")); mkdirSync(join(root, "docs", "orchestration-input"), { recursive: true }); writeFileSync(join(root, "src", "base.mjs"), "export{}\n"); writeFileSync(join(root, "docs", "orchestration-input", "inventory.json"), "{}"); writeFileSync(join(root, "package.json"), JSON.stringify({ packageManager: "npm@10", scripts: {} })); writeFileSync(join(root, "package-lock.json"), "{}"); git(root, ["add", "."]); git(root, ["-c", "user.name=t", "-c", "user.email=t@e", "commit", "-m", "base"]); const client = new Client(plan); const roles = Object.fromEntries(["bootstrap","planner","backend","frontend","database","qa","security","devops"].map((r) => [r, { sandbox: r === "backend" ? "workspace-write" : "read-only", approvalPolicy: "never", tokenBudget: 100, usesWorktree: r === "backend" }])); return { root, client, router: new SwarmRouter({ repository: root, runtimeDir: join(root,"runtime"), baseRef:"main", model:"fake", project:{name:"lineage",documentationDir:"docs/orchestration-input",generatedDir:"docs/orchestration-generated",productRoots:[]}, router:{maxConcurrentTasks:1,maxChildrenPerTask:10,maxDelegationDepth:5,maxPlanTasks:5,defaultParentBudget:1000,turnTimeoutMs:1000}, autonomy:{mode:"autonomous",autoApproveWorkflowGates:true,autoRemediate:true}, budget:{weeklyTokenLimit:10000,weeklyWindowDays:7}, quota:{throttleAtUsedPercent:90,throttleWhenUnavailable:false},roles,appServerClientFactory:()=>client }) }; }
test("planner writer edge materializes artifact lineage and integration order", async () => { const x=setup({tasks:[task("writer-a","Write A"),task("writer-b","Write B",["writer-a"])]}); try { await x.router.ensureProjectOverlay(); x.router.startProject(); await x.router.runUntilIdle(); const a=x.router.list().find((v)=>v.title==="Write A"), b=x.router.list().find((v)=>v.title==="Write B"), aa=x.router.store.workerArtifact(a.id), ba=x.router.store.workerArtifact(b.id); assert.equal(x.client.bases.get("b"),aa.headSha); assert.equal(b.artifactBaseSha,aa.headSha); assert.deepEqual(ba.dependencies,[a.id]); assert.deepEqual((await x.router.integrateFinalized([b.id,a.id])).manifest.appliedArtifacts,[a.id,b.id]); } finally { x.router.close(); rmSync(x.root,{recursive:true,force:true}); } });
test("planner rejects writer artifact fan-in for repair", async () => { const x=setup({tasks:[task("writer-a","Write A"),task("writer-c","Write C"),task("writer-b","Write B",["writer-a","writer-c"])]}); try { await x.router.ensureProjectOverlay(); x.router.startProject(); await x.router.runUntilIdle(); const p=x.router.list().find((v)=>v.role==="planner"); assert.equal(p.status,"failed"); assert.match(p.error,/multiple writer artifact predecessors/); } finally { x.router.close(); rmSync(x.root,{recursive:true,force:true}); } });
