"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, Favorite, Guide, isUnlocked, photoFor, Place, UnlockedPlace } from "../lib/api";
import { Map } from "./Map";

type Ratings = { average: number; ratings: { id: number; stars: number; comment?: string; createdAt: string }[] };
function RatingWidget({ city, place }: { city: string; place: UnlockedPlace }) {
  const [data, setData] = useState<Ratings | null>(null); const [stars, setStars] = useState(5); const [comment, setComment] = useState(""); const [message, setMessage] = useState("");
  const load = () => api<Ratings>(`/guides/${encodeURIComponent(city)}/places/${encodeURIComponent(place.slug)}/ratings`).then(setData).catch(() => setData(null));
  useEffect(() => { load(); }, [city, place.slug]);
  async function submit(event: FormEvent) { event.preventDefault(); try { await api(`/guides/${encodeURIComponent(city)}/places/${encodeURIComponent(place.slug)}/ratings`, { method: "POST", body: JSON.stringify({ stars, comment }) }); setMessage("Thank you — your rating is saved."); load(); } catch (error) { setMessage(error instanceof Error ? `${error.message} Sign in to leave a rating.` : "Unable to save rating."); } }
  return <div className="rating"><div className="rating-summary"><span aria-hidden>★</span> {data?.average ? `${Number(data.average).toFixed(1)} from ${data.ratings.length} ${data.ratings.length === 1 ? "rating" : "ratings"}` : "Be the first to rate this place"}</div><form onSubmit={submit}><div className="star-picker" aria-label="Your rating">{[1,2,3,4,5].map((value) => <button type="button" className={value <= stars ? "selected" : ""} onClick={() => setStars(value)} key={value} aria-label={`${value} stars`}>★</button>)}</div><textarea value={comment} onChange={e => setComment(e.target.value)} maxLength={2000} placeholder="A helpful note for other wanderers (optional)" /><button className="text-button">Save rating</button></form>{message && <p className="widget-note">{message}</p>}</div>;
}
function PlaceCard({ city, place, favorite, onFavorite, onPurchase }: { city: string; place: Place; favorite?: Favorite; onFavorite: (place: UnlockedPlace, favorite?: Favorite) => void; onPurchase: () => void }) {
  const locked = !isUnlocked(place);
  return <article className={`place-card ${locked ? "locked" : ""}`}><div className="place-media"><img src={photoFor(city, place.slug)} alt={place.name} /><div className="place-media-gradient" /><div className="place-media-copy"><p className="place-number">{locked ? "Member place" : place.is_preview ? "Free preview" : "Unlocked place"}</p><h3>{place.name}</h3><p className="why-go">{place.why_go}</p>{locked && <button type="button" className="button buy-to-unlock" onClick={onPurchase}>Buy to unlock</button>}</div></div>{locked ? <div className="place-body"><div className="lock-line">⌁ Full story, directions and details are locked</div></div> : <div className="place-body"><div className="place-card-head"><p className="place-number">Practical details</p><button className={`save-button ${favorite ? "saved" : ""}`} onClick={() => onFavorite(place, favorite)} aria-label={favorite ? `Remove ${place.name} from saved places` : `Save ${place.name}`}>♡ <span>{favorite ? "Saved" : "Save"}</span></button></div><p className="description">{place.description}</p><div className="chips"><span>⌖ {place.how_to_get_there}</span><span>◌ {place.cost}</span><span>↗ {place.booking_tip}</span></div><RatingWidget city={city} place={place} /></div>}</article>;
}
export function GuideClient({ city }: { city: string }) {
  const [guide, setGuide] = useState<Guide | null>(null); const [favorites, setFavorites] = useState<Favorite[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api<Guide>(`/guides/${encodeURIComponent(city)}`).then(setGuide).catch(() => setMessage("We couldn’t load this guide. Check that the API is running.")).finally(() => setLoading(false)); api<Favorite[]>("/favorites").then(setFavorites).catch(() => setFavorites([])); };
  useEffect(load, [city]);
  const visible = useMemo(() => guide?.places.filter(isUnlocked) ?? [], [guide]);
  async function purchase() { try { await api(`/guides/${encodeURIComponent(city)}/purchase`, { method: "POST" }); setMessage("Guide unlocked — happy wandering."); load(); } catch (error) { setMessage(error instanceof Error ? `${error.message} Sign in to unlock this guide.` : "Sign in to unlock this guide."); } }
  async function toggleFavorite(place: UnlockedPlace, current?: Favorite) { try { if (current) { await api(`/favorites/${current.id}`, { method: "DELETE" }); setFavorites(list => list.filter(item => item.id !== current.id)); } else { const next = await api<Favorite>("/favorites", { method: "POST", body: JSON.stringify({ city: guide?.city, placeSlug: place.slug }) }); setFavorites(list => [...list, next]); } } catch (error) { setMessage(error instanceof Error ? `${error.message} Sign in to save places.` : "Sign in to save places."); } }
  if (loading) return <main className="loading">Finding the good stuff…</main>;
  if (!guide) return <main className="loading">{message || "Guide not found."}</main>;
  return <main><section className={`guide-hero ${city.toLowerCase()}`}><div><p className="eyebrow">A wanderwell city guide</p><h1>{guide.city}, <em>slowly.</em></h1><p>{guide.intro}</p>{!guide.purchased && <button className="button button-light" onClick={purchase}>Unlock the complete guide · €{guide.price.toFixed(2)}</button>}</div></section>{message && <p className="toast">{message}</p>}{!guide.purchased && <section className="unlock-banner"><span>✦</span><div><p className="eyebrow">Three places are on us</p><h2>The rest of {guide.city} is waiting.</h2></div><button className="button button-dark" onClick={purchase}>Unlock for €{guide.price.toFixed(2)}</button></section>}<section className="guide-content"><div className="section-heading"><div><p className="eyebrow">{guide.purchased ? "Your complete route" : "A taste of the city"}</p><h2>Places worth your time.</h2></div><p>{guide.purchased ? "All the practical detail is here — take it at your own pace." : "Explore the free preview below, then unlock the guide for all 15 places and their practical details."}</p></div><Map city={guide.city} places={visible} /><div className="places-grid">{guide.places.map(place => <PlaceCard key={place.slug} city={guide.city} place={place} favorite={favorites.find(item => item.city.toLowerCase() === guide.city.toLowerCase() && item.placeSlug === place.slug)} onFavorite={toggleFavorite} onPurchase={purchase} />)}</div>{!guide.purchased && <div className="bottom-cta"><p className="eyebrow">Ready when you are</p><h2>Make {guide.city} your own.</h2><button className="button button-dark" onClick={purchase}>Unlock all 15 places · €{guide.price.toFixed(2)}</button><p>Mock purchase — no card details, no real charge.</p></div>}</section></main>;
}
